// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFI-79dTl9292bngifzwzLq15XMWHM0Q',
    appId: '1:540521568313:web:74d4dd9c0ce814540495e8',
    messagingSenderId: '540521568313',
    projectId: 'spacenews-core-9d5a4',
    authDomain: 'spacenews-core-9d5a4.firebaseapp.com',
    storageBucket: 'spacenews-core-9d5a4.firebasestorage.app',
    measurementId: 'G-YPWHY5DENS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYo5WPFtPQjYDAPDvOOepvnXVODeCoDbA',
    appId: '1:540521568313:android:1b7abaa92a37b5b90495e8',
    messagingSenderId: '540521568313',
    projectId: 'spacenews-core-9d5a4',
    storageBucket: 'spacenews-core-9d5a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxUpq-C7XwhbJ1rhGAwxUvjwADJqWWRc8',
    appId: '1:540521568313:ios:0eca60aabfcfaee70495e8',
    messagingSenderId: '540521568313',
    projectId: 'spacenews-core-9d5a4',
    storageBucket: 'spacenews-core-9d5a4.firebasestorage.app',
    iosClientId: '540521568313-s2rds55ru66nf4pepmrhacjjtsrjbuq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pabremFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxUpq-C7XwhbJ1rhGAwxUvjwADJqWWRc8',
    appId: '1:540521568313:ios:0eca60aabfcfaee70495e8',
    messagingSenderId: '540521568313',
    projectId: 'spacenews-core-9d5a4',
    storageBucket: 'spacenews-core-9d5a4.firebasestorage.app',
    iosClientId: '540521568313-s2rds55ru66nf4pepmrhacjjtsrjbuq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pabremFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFI-79dTl9292bngifzwzLq15XMWHM0Q',
    appId: '1:540521568313:web:c8fde1c0b0796a690495e8',
    messagingSenderId: '540521568313',
    projectId: 'spacenews-core-9d5a4',
    authDomain: 'spacenews-core-9d5a4.firebaseapp.com',
    storageBucket: 'spacenews-core-9d5a4.firebasestorage.app',
    measurementId: 'G-NLH1JGY2WD',
  );
}
